import {topics,parameters,question,correct,cubes} from './content.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY='texas-math-lab-v1';
let store={learner:'a',profiles:{a:{},b:{}}},storageOK=true;try{let v=JSON.parse(localStorage.getItem(KEY));if(v&&v.profiles?.a&&v.profiles?.b&&['a','b'].includes(v.learner))store=v}catch{storageOK=false}
let id='number',level=0,stage='explore',seed=481,english=false,model={},quizIndex=0,quiz=[],help=false,attempts=0,answered=false,mixed=false,results=[],yaw=-.65,pitch=.55;
function profile(){return store.profiles[store.learner]}function topic(){return topics.find(t=>t.id===id)}function entry(){let key=id+'-'+level;return profile()[key]??={attempts:0,independent:0,supported:0,errors:0,sessions:0,note:'',last:0}}
function save(){try{store.current={id,level,stage,seed,english};localStorage.setItem(KEY,JSON.stringify(store));storageOK=true}catch{storageOK=false}$('#storageStatus').textContent=storageOK?'学习记录保存在这台设备':'浏览器未允许保存；本次仍可练习'}
try{let c=store.current;if(c&&topics.some(t=>t.id===c.id)&&[0,1,2].includes(c.level)){id=c.id;level=c.level;seed=Number.isSafeInteger(c.seed)?c.seed:481;english=!!c.english}}catch{}
function message(text,error=false){$('#feedback').textContent=text;$('#feedback').className=error?'error':''}
function initModel(){let p=parameters(id,level,seed);model={...p,moved:0,shaded:p.a||0,split:false,showBars:false};yaw=-.65;pitch=.55}
function setTopic(next){id=next;level=0;stage='explore';mixed=false;initModel();render()}
function render(){let t=topic();$('#learner').value=store.learner;$('#topics').innerHTML=topics.map((x,i)=>'<button data-topic="'+x.id+'" class="'+(id===x.id?'active':'')+'" aria-pressed="'+(id===x.id)+'"><span class="topic-icon">'+x.icon+'</span><span>'+x.title+'<small>'+x.en+'</small></span></button>').join('');$('#eyebrow').textContent=t.en+' / 约 5 分钟';$('#title').textContent=t.title;$('#intro').textContent=t.intro;$('#number').textContent='0'+(topics.indexOf(t)+1);$('#lesson').innerHTML=t.lessons.map((l,i)=>'<option value="'+i+'">'+l[0]+' · '+l[1]+'</option>').join('');$('#lesson').value=level;$$('[data-stage]').forEach(b=>{b.classList.toggle('active',b.dataset.stage===stage);b.setAttribute('aria-selected',b.dataset.stage===stage)});$('#language').textContent=english?'题目：English':'题目：中文';$('#language').setAttribute('aria-pressed',english);$('#reflect').textContent=t.reflect;$('#note').value=entry().note||'';message('');if(stage==='explore')drawLab();else drawQuestion();save()}
const head=(title,sub)=>'<div class="lab-head"><div><h3>'+title+'</h3><p>'+sub+'</p></div><span class="badge">动手实验</span></div>';
const controls=html=>'<div class="lab-controls">'+html+'</div>';
function drawLab(){let t=topic(),p=model,body='',ctrl='',title='',sub='';
if(id==='number'){title=level===2?'把十分之一凑成整数':'试着先凑满一个十';sub='点金色珠子，或把它拖到左边空格。想一想总数变了吗？';let left=p.a+p.moved,right=p.b-p.moved;function frame(count,first){return '<div class="frame-wrap"><div class="frame" data-drop="'+(first?'left':'right')+'">'+Array.from({length:10},(_,i)=>'<div class="cell">'+(i<count?'<button class="bead '+(!first||i>=p.a?'b':'')+'" data-bead="'+(first?'back':'move')+'" '+(!first?'draggable="true"':'')+' aria-label="'+(first?'把补入的珠子放回右边':'移一颗到左边')+'">'+(level===2?'·':'1')+'</button>':'')+'</div>').join('')+'</div><p class="frame-label">'+(first?'第一组':'第二组')+' · '+(count*p.unit).toFixed(level===2?1:0)+'</p></div>'}body='<div class="frames">'+frame(left,true)+frame(right,false)+'</div><p class="equation">'+((p.tens+left)*p.unit).toFixed(level===2?1:0)+' ＋ '+(right*p.unit).toFixed(level===2?1:0)+'</p>'+(p.tens?'<p style="text-align:center">另有 '+p.tens+'，保持不动。</p>':'');ctrl='<button data-act="move" class="primary">移一颗到左边</button><button data-act="back">放回一颗</button><button data-act="resetModel">重来</button>'}
if(id==='array'){title='每一行一样多';sub='改变行数和列数。再拆成两块，比较总数。';body='<div class="mini-controls">'+counter('rows','行',p.rows)+counter('cols','列',p.cols)+'</div><div class="array" style="grid-template-columns:repeat('+p.cols+',28px)">'+Array.from({length:p.rows*p.cols},(_,i)=>'<span class="'+(p.split&&i%p.cols>=2?'alt':'')+'"></span>').join('')+'</div><p class="equation">'+p.rows+' × '+p.cols+' = '+p.rows*p.cols+'</p>';ctrl='<button class="primary" data-act="split">'+(p.split?'合起来':'拆成两块')+'</button><span>'+(p.split?p.rows+'×2 + '+p.rows+'×'+(p.cols-2)+' = '+p.rows*p.cols:'每行 '+p.cols+' 个，共 '+p.rows+' 行')+'</span>'}
if(id==='fraction'){title='一样大的整体';sub='点每一份来涂色或取消。上下两条一样长。';body='<div class="fraction-bar">'+Array.from({length:p.d},(_,i)=>'<button data-part="'+i+'" class="'+(i<p.shaded?'filled':'')+'" aria-label="涂到第 '+(i+1)+' 份">'+(i+1)+'</button>').join('')+'</div><p class="equation">'+p.shaded+' / '+p.d+'</p>'+(level===1?'<div class="fraction-bar">'+Array.from({length:p.d*2},(_,i)=>'<button disabled class="'+(i<p.shaded*2?'filled':'')+'"></button>').join('')+'</div><p style="text-align:center">'+p.shaded+'/'+p.d+' = '+p.shaded*2+'/'+p.d*2+'</p>':'')+(level===2?'<p style="text-align:center">试把 '+p.a+'/'+p.d+' 与 '+p.b+'/'+p.d+' 合起来：涂 '+(p.a+p.b)+' 份。</p>':'')+'<div class="numberline"><span>0</span><span>1/2</span><span>1</span></div>';ctrl='<button data-act="less">少涂一份</button><button class="primary" data-act="more">多涂一份</button><span>整体平均分成 '+p.d+' 份</span>'}
if(id==='space'){title='先猜，再换一个角度';sub='拖动积木旋转；也可以用方向键或视角按钮。';body='<div class="canvas-wrap"><canvas id="blocks" width="650" height="320" tabindex="0" role="img" aria-label="可旋转的单位积木模型，左右方向键旋转，上下方向键调整俯视角度"></canvas></div><div class="view-controls"><button data-view="front">正面</button><button data-view="top">上面</button><button data-view="side">右面</button><button data-view="free">立体</button></div>';ctrl='<span>'+p.w+' 列 × '+p.d+' 排'+(level===2?' × '+p.h+' 层':' · 高度不一样')+'</span><button data-act="count" class="primary">检查积木数量</button>'}
if(id==='story'){title='先找已知，再找问题';sub='先读故事，预测用哪一种运算。展开数量图检查。';let q=question(id,level,seed);body='<p style="font-size:22px;max-width:580px;margin:10px auto 24px">'+(english?q.en:q.zh)+'</p>'+(p.showBars?storyBars(p):'<div style="text-align:center;padding:30px"><span class="pill">先想一想：求一共，还是相差？</span></div>');ctrl='<button data-act="bars" class="primary">'+(p.showBars?'收起数量图':'打开数量图')+'</button>'}
if(id==='logic'){title=level===0?'每一步，怎样变化？':level===1?'有顺序，就不容易漏掉':'倒过来检查';sub=level===0?'观察相邻两个数之间的变化。':level===1?'依次试每行放几个。只记录能排整齐的情况。':'先看一个例子，再自己解决不同的题。';body=level===0?'<div class="numbers">'+[0,1,2].map(i=>'<span>'+(p.start+i*p.step)+'</span>').join('')+'<span>?</span></div>':level===1?'<p class="equation">'+p.target+' 个方块</p><div class="mini-controls">'+counter('trial','每行',p.trial||1)+'</div><p style="text-align:center">'+(p.target%(p.trial||1)===0?'可以排整齐：'+p.target/(p.trial||1)+' 行，每行 '+(p.trial||1)+' 个。':'不能排整齐，还剩 '+p.target%(p.trial||1)+' 个。')+'</p>':'<div class="numbers"><span>?</span><span>× 3</span><span>＋ 4</span><span>19</span></div><p style="text-align:center">先撤掉 ＋4，再撤掉 ×3。想好后查看检查。</p>';ctrl='<button data-act="logicHint" class="primary">查看思路</button>'}
$('#activity').innerHTML='<div class="lab">'+head(title,sub)+'<div class="workbench">'+body+'</div>'+controls(ctrl)+'<p class="explain">'+t.lessons[level][2]+'</p></div><div style="text-align:right;margin-top:15px"><button class="primary" data-act="practice">收起教具，独立试试 →</button></div>';
if(id==='space')setupCanvas();bindDrag()}
function counter(key,label,value){return '<div class="counter"><span>'+label+'</span><button data-counter="'+key+'" data-delta="-1" aria-label="'+label+'减少">−</button><output>'+value+'</output><button data-counter="'+key+'" data-delta="1" aria-label="'+label+'增加">＋</button></div>'}
function storyBars(p){return '<div class="story-bars">'+(level===0?'<div class="story-line"><span>小安</span><div class="bar" style="width:'+p.a*16+'px">'+p.a+'</div></div><div class="story-line"><span>小贝</span><div class="bar orange" style="width:'+p.b*16+'px">'+p.b+'</div></div>':'<div class="story-line" style="gap:4px;flex-wrap:wrap">'+Array.from({length:p.a},()=>'<div class="bar" style="width:42px">'+p.b+'</div>').join('')+'</div>'+(level===2?'<p>先求 '+p.a+' 组，每组 '+p.b+'。然后拿走 '+p.c+'。</p>':''))+'</div>'}
function startQuiz(challenge=false,isMixed=false){stage=challenge?'challenge':'practice';mixed=isMixed;quizIndex=0;help=false;attempts=0;answered=false;results=[];quiz=isMixed?topics.map((t,i)=>({id:t.id,level,seed:seed+i*101,q:question(t.id,level,seed+i*101,i%3)})):Array.from({length:challenge?1:3},(_,i)=>({id,level,seed:seed+i*101,q:question(id,level,seed+i*101,i,challenge)}));render()}
function drawQuestion(){if(!quiz.length){startQuiz(stage==='challenge');return}if(quizIndex>=quiz.length){showSummary();return}let item=quiz[quizIndex],q=item.q;$('#activity').innerHTML='<div class="lab"><div class="lab-head"><div><h3>'+(mixed?'综合练习 · '+topics.find(t=>t.id===item.id).title:stage==='challenge'?'数学拓展挑战':'独立试试')+'</h3><p>没有计时。需要时可以看提示，之后再练独立完成。</p></div><span class="badge">'+(quizIndex+1)+' / '+quiz.length+'</span></div><div class="quiz"><div class="progress-track">'+quiz.map((_,i)=>'<span class="'+(i<quizIndex?'done':i===quizIndex?'current':'')+'"></span>').join('')+'</div><h3>'+(english?q.en:q.zh)+'</h3><form id="answerForm"><label for="answer">你的答案'+(q.unit?'（'+q.unit+'）':'')+'</label><div class="answer-row"><input id="answer" autocomplete="off" inputmode="text" placeholder="数字或分数" required '+(answered?'disabled':'')+'><button class="primary" '+(answered?'disabled':'')+'>检查答案</button><button type="button" data-act="hint">给我一点提示</button></div></form><div id="hintBox" class="hint" '+(help?'':'hidden')+'>'+(help?q.hint:'')+'</div><button data-act="next" id="nextQuestion" '+(answered?'':'hidden')+' style="margin-top:18px">继续 →</button></div></div>';$('#answerForm').onsubmit=e=>{e.preventDefault();checkAnswer()}}
function checkAnswer(){if(answered)return;let raw=$('#answer').value,q=quiz[quizIndex].q;if(!raw.trim())return;attempts++;let item=quiz[quizIndex],key=item.id+'-'+item.level,e=profile()[key]??={attempts:0,independent:0,supported:0,errors:0,sessions:0,note:'',last:0};e.attempts++;if(correct(raw,q.answer)){answered=true;let solo=!help&&attempts===1;e[solo?'independent':'supported']++;e.last=Date.now();results.push({topic:topics.find(t=>t.id===item.id).title,solo,why:q.why});message((solo?'你独立完成了。':'借助检查，你找到了答案。')+q.why);$('#answer').disabled=true;$('#answerForm button[type="submit"],#answerForm .primary').disabled=true;$('#nextQuestion').hidden=false}else{e.errors++;message('还没对上。'+q.hint+' 可以修改后再试，或打开提示。',true)}save()}
function showSummary(){let solo=results.filter(r=>r.solo).length;entry().sessions++;save();$('#activity').innerHTML='<div class="lab summary"><p class="overline">这一小段，完成了</p><h3>'+solo+' / '+results.length+' 道独立完成</h3><p>这里记录的是本次练习表现，还需要隔天换题再检查。</p><ul>'+results.map(r=>'<li>'+r.topic+'：'+(r.solo?'独立完成':'借助提示或修改后完成')+'</li>').join('')+'</ul><div class="answer-row"><button data-act="explore">回到实验</button><button class="primary" data-act="again">换题再练</button></div></div>';message('想一想：哪一步最有用？说清楚以后就可以休息。')}
function moveBead(delta){if(delta>0&&model.a+model.moved<10&&model.moved<model.b)model.moved++;else if(delta<0&&model.moved>0)model.moved--;drawLab();message(model.a+model.moved===10?'左边凑满了！移动前后总数没有改变。':'观察两组数量，一组增加，另一组就减少。')}
function bindDrag(){if(id!=='number')return;$$('[draggable]').forEach(el=>el.ondragstart=e=>e.dataTransfer.setData('text/plain','bead'));let target=$('[data-drop="left"]');if(target){target.ondragover=e=>e.preventDefault();target.ondrop=e=>{e.preventDefault();if(e.dataTransfer.getData('text/plain')==='bead')moveBead(1)}}}
$('#activity').addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;let act=b.dataset.act;
if(b.dataset.bead){moveBead(b.dataset.bead==='move'?1:-1);return}
if(b.dataset.counter){let k=b.dataset.counter,max=k==='trial'?model.target:9;model[k]=Math.max(k==='trial'?1:2,Math.min(max,(model[k]||1)+Number(b.dataset.delta)));drawLab();return}
if(b.dataset.part!==undefined){let n=Number(b.dataset.part)+1;model.shaded=n===model.shaded?n-1:n;drawLab();return}
if(b.dataset.view){[yaw,pitch]=({front:[0,0],top:[0,Math.PI/2],side:[Math.PI/2,0],free:[-.65,.55]})[b.dataset.view];drawBlocks();return}
if(act==='practice'){startQuiz();return}if(act==='explore'){stage='explore';mixed=false;render();return}if(act==='again'){seed++;startQuiz(stage==='challenge',mixed);return}
if(act==='move'||act==='back'){moveBead(act==='move'?1:-1);return}
if(act==='resetModel'){initModel();drawLab();message('已经回到开始状态。');return}
if(act==='split'){model.split=!model.split;drawLab();return}
if(act==='more'||act==='less'){model.shaded=Math.max(0,Math.min(model.d,model.shaded+(act==='more'?1:-1)));drawLab();return}
if(act==='bars'){model.showBars=!model.showBars;drawLab();return}
if(act==='count'){message('共有 '+cubes(model,level).length+' 个单位积木。按柱或按层数一数，再核对。');return}
if(act==='logicHint'){message(level===0?'相邻两项都相差 '+model.step+'。再加一次试试。':level===1?'把行数和每行个数写成一对。互换后一样的排法，只算一次。':'19−4=15，再算 15÷3=5。检查：5×3＋4=19。');return}
if(act==='hint'){help=true;$('#hintBox').hidden=false;$('#hintBox').textContent=quiz[quizIndex].q.hint+' '+quiz[quizIndex].q.why;message('提示已打开。这题会记为借助帮助完成。');return}
if(act==='next'){quizIndex++;help=false;attempts=0;answered=false;message('');drawQuestion();return}
});
function setupCanvas(){let c=$('#blocks'),down=null;c.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!down)return;yaw+=(e.clientX-down[0])*.01;pitch=Math.max(-1.5,Math.min(1.5,pitch+(e.clientY-down[1])*.01));down=[e.clientX,e.clientY];drawBlocks()});for(let event of ['pointerup','pointercancel','lostpointercapture'])c.addEventListener(event,()=>down=null);c.onkeydown=e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();if(e.key==='ArrowLeft')yaw-=.15;if(e.key==='ArrowRight')yaw+=.15;if(e.key==='ArrowUp')pitch=Math.min(1.5,pitch+.15);if(e.key==='ArrowDown')pitch=Math.max(-1.5,pitch-.15);drawBlocks()};drawBlocks()}
function drawBlocks(){let c=$('#blocks');if(!c)return;let ratio=devicePixelRatio||1;let W=c.clientWidth,H=c.clientHeight;c.width=W*ratio;c.height=H*ratio;let g=c.getContext('2d');g.scale(ratio,ratio);g.clearRect(0,0,W,H);let faces=[],p=model,cs=cubes(p,level),scale=Math.min(46,W/(p.w+p.d+1));function transform([x,y,z]){x-=p.w/2;y-=1.3;z-=p.d/2;let xx=x*Math.cos(yaw)+z*Math.sin(yaw),zz=-x*Math.sin(yaw)+z*Math.cos(yaw),yy=y*Math.cos(pitch)-zz*Math.sin(pitch);return[W/2+xx*scale,H/2-yy*scale,y*Math.sin(pitch)+zz*Math.cos(pitch)]}
for(let[x,y,z]of cs){let defs=[[[0,1,0],[1,1,0],[1,1,1],[0,1,1]],[[0,0,1],[1,0,1],[1,1,1],[0,1,1]],[[1,0,0],[0,0,0],[0,1,0],[1,1,0]],[[1,0,1],[1,0,0],[1,1,0],[1,1,1]],[[0,0,0],[0,0,1],[0,1,1],[0,1,0]],[[0,0,0],[1,0,0],[1,0,1],[0,0,1]]];defs.forEach((vs,i)=>{let poly=vs.map(v=>transform([x+v[0],y+v[1],z+v[2]]));faces.push({poly,z:poly.reduce((s,v)=>s+v[2],0)/4,color:['#a7e5bc','#36978b','#36978b','#247468','#247468','#1c5a53'][i]})})}
faces.sort((a,b)=>a.z-b.z);for(let f of faces){g.beginPath();f.poly.forEach((v,i)=>i?g.lineTo(v[0],v[1]):g.moveTo(v[0],v[1]));g.closePath();g.fillStyle=f.color;g.fill();g.strokeStyle='#174f4b';g.lineWidth=2;g.stroke()}g.fillStyle='#3a6669';g.font='14px system-ui';g.textAlign='center';g.fillText('拖动旋转 · 方向键也可以操作',W/2,H-10)}
$('#topics').onclick=e=>{let b=e.target.closest('[data-topic]');if(b)setTopic(b.dataset.topic)};
$('#lesson').onchange=e=>{level=Number(e.target.value);stage='explore';mixed=false;initModel();render()};
$$('[data-stage]').forEach(b=>b.onclick=()=>{if(b.dataset.stage==='explore'){stage='explore';mixed=false;render()}else startQuiz(b.dataset.stage==='challenge')});
$('#newProblem').onclick=()=>{seed++;initModel();if(stage==='explore')render();else startQuiz(stage==='challenge',mixed)};
$('#language').onclick=()=>{english=!english;render()};
$('#learner').onchange=e=>{store.learner=e.target.value;quiz=[];stage='explore';initModel();render()};
$('#note').oninput=e=>{entry().note=e.target.value;save()};
$('#mixed').onclick=()=>startQuiz(false,true);
function dialog(title,html){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=html;$('#dialog').showModal()}
$('#closeDialog').onclick=()=>$('#dialog').close();
$('#parents').onclick=()=>dialog('陪孩子发现，而不是代替作答','<p>先问“你准备怎么试？”再给孩子时间。每次完成一个小任务即可休息。</p><ol><li>动手发现：观察模型，改变条件。</li><li>独立试试：收起模型，解答不同形式的问题。</li><li>想深一点：用有序列举、逆向思考解释原因。</li><li>隔天再练：检查离开提示后是否仍然会。</li></ol><p>题目可切换英文，帮助连接学校数学语言。两个学习者的记录分开保存在设备上。</p><p>当前是 18 个主题任务的起步版，覆盖部分 K–5 知识。综合练习是原创练习，不是官方 STAAR 试卷，也不预测考试分数。</p><a href="guide.html">查看已覆盖内容、官方资料与安装说明 →</a>');
$('#records').onclick=()=>{let rows=Object.entries(profile()).filter(([k])=>/^[a-z]+-[012]$/.test(k));dialog('学习足迹 · '+(store.learner==='a'?'探索者 A':'探索者 B'),'<p>独立＝首次答对且未使用提示。练习表现不等于长期掌握；建议隔天换题再试。</p><table><thead><tr><th>任务</th><th>独立</th><th>有帮助</th><th>错误尝试</th></tr></thead><tbody>'+rows.map(([k,e])=>{let[t,l]=k.split('-');return '<tr><td>'+topics.find(x=>x.id===t).lessons[Number(l)][0]+'</td><td>'+e.independent+'</td><td>'+e.supported+'</td><td>'+e.errors+'</td></tr>'}).join('')+'</tbody></table>'+(rows.length?'':'<p>完成一道练习后，这里就会留下足迹。</p>')+'<button id="clearRecords" class="danger">清除本学习者记录</button>');$('#clearRecords').onclick=()=>{if(confirm('确认清除当前学习者的练习记录与笔记？不能撤销，另一位学习者不受影响。')){store.profiles[store.learner]={};save();$('#dialog').close();render()}}};
initModel();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{$('#storageStatus').textContent+=' · 离线缓存尚未就绪'});
