import './cloud-sync.js';
import{PLACE_TRACKS,PLACE_CHAIN,PLACE_DIAGNOSTIC,recommendPlaceTrack,valueOfCounts,standardizeTrade,compareNumbers,formatValue,createBlankPlaceLearner}from'./place-data.js';

const $=s=>document.querySelector(s),storageKey='mathlab-place-v1',memory={};
function blankStore(){return{a:createBlankPlaceLearner(),b:createBlankPlaceLearner(),learner:'a'}}
function readStore(){try{return JSON.parse(localStorage.getItem(storageKey))||blankStore()}catch{return memory.data||blankStore()}}
let store=readStore(),learner=store.learner||'a',state=store[learner]||createBlankPlaceLearner(),hintLevel=0,attempts=0,sessionMissionId=null,work={};
function ensureState(){const blank=createBlankPlaceLearner();state={...blank,...state,diagnostic:{...blank.diagnostic,...state.diagnostic},missions:{...state.missions},sessions:{...state.sessions},evidence:{...blank.evidence,...state.evidence},family:{...blank.family,...state.family}}}
function save(){state.updatedAt=new Date().toISOString();store={...readStore(),[learner]:state,learner};memory.data=store;try{localStorage.setItem(storageKey,JSON.stringify(store));$('#saveStatus').textContent='Saved offline · cloud sync follows parent sign-in'}catch{$('#saveStatus').textContent='Progress lasts until this page closes.'}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function feedback(text,type=''){const el=$('#feedback');el.textContent=text;el.className='feedback '+type}
function track(){return PLACE_TRACKS[state.track||'explorer']}
function done(i){return Boolean(state.missions[PLACE_CHAIN.missions[i].id]?.complete)}
function unlocked(i){return i===0||done(i-1)}
function mark(dim,independent=true){if(independent)state.evidence[dim]='independent';else if(state.evidence[dim]==='unknown')state.evidence[dim]='learning'}
function loadSession(id){sessionMissionId=id;const saved=state.sessions[id]||{attempts:0,hints:0,work:{}};attempts=Number(saved.attempts)||0;hintLevel=Number(saved.hints)||0;work=saved.work||{}}
function saveSession(nextWork=work){if(!sessionMissionId)return;work=nextWork;state.sessions[sessionMissionId]={attempts,hints:hintLevel,work};save()}
function complete(i,dims=[],pending=false,preview=false){const m=PLACE_CHAIN.missions[i];state.missions[m.id]={complete:!preview,preview,attempts,hints:hintLevel,completedAt:new Date().toISOString(),track:state.track};dims.forEach(d=>mark(d,attempts<=1&&hintLevel===0&&!preview));if(pending){state.retestDue=Date.now()+20*60*60*1000;state.evidence.explanation=state.evidence.explanation==='unknown'?'learning':state.evidence.explanation}if(!preview&&i<4)state.activeMission=i+1;delete state.sessions[m.id];attempts=0;hintLevel=0;work={};sessionMissionId=null;save();setTimeout(render,450)}
function tryOnce(){attempts++;saveSession()}
function hint(text){return hintLevel?`<div class="hint-box">${esc(text)}</div>`:''}
function controls(){return `<div class="answer-row"><button class="secondary" data-action="hint">Give me one hint</button></div>`}
function placeName(place,count=2){return count===1?place.name.replace(/s$/,''):place.name}
function numberCard(value,places){const text=formatValue(value);const [whole,decimal='']=text.split('.');const digits=(whole+decimal.padEnd(places.filter(p=>p.value<1).length,'0')).padStart(places.length,'0').slice(-places.length);return `<div class="number-card"><strong>${text}</strong><div style="grid-template-columns:repeat(${places.length},1fr)">${places.map((p,i)=>`<span><b>${digits[i]||'0'}</b><small>${p.name}</small></span>`).join('')}</div></div>`}
function placeBoard(counts,editable=false){const t=track();return `<div class="place-board" style="--place-columns:${t.places.length}">${t.places.map((p,i)=>`<section class="place-column"><header><strong>${p.name}</strong><small>each is worth ${formatValue(p.value)}</small></header><div class="place-count">${counts[i]}</div><div class="unit-stack" aria-label="${counts[i]} ${p.name}">${Array.from({length:Math.min(10,counts[i])},()=>'<i></i>').join('')}${counts[i]>10?`<b>+${counts[i]-10}</b>`:''}</div>${editable?`<div class="stepper"><button data-count="${i}" data-delta="-1" aria-label="Remove one ${placeName(p,1)}">−</button><button data-count="${i}" data-delta="1" aria-label="Add one ${placeName(p,1)}">＋</button></div>`:''}</section>`).join('')}</div><p class="equation place-total">Total value: <strong>${formatValue(valueOfCounts(counts,t.places))}</strong></p>`}

function renderDiagnostic(){const d=state.diagnostic;if(d.index>=PLACE_DIAGNOSTIC.length){state.track=state.track||recommendPlaceTrack(d.score);const t=track();$('#activity').innerHTML=`<div class="complete-card"><div class="big-check">✓</div><p class="eyebrow">STARTING DEPTH FOUND</p><h3>${t.label}</h3><p>${t.description}</p><p class="microcopy">This chooses useful numbers. It is not a grade label.</p><button class="primary" data-action="start">Build a number →</button></div>`;return}const q=PLACE_DIAGNOSTIC[d.index];$('#activity').innerHTML=`<div class="diagnostic-progress"><span style="width:${d.index/PLACE_DIAGNOSTIC.length*100}%"></span></div><p class="eyebrow">QUESTION ${d.index+1} OF ${PLACE_DIAGNOSTIC.length}</p><h3>${esc(q.prompt)}</h3><div class="answer-grid">${q.choices.map((x,i)=>`<button class="choice" data-diagnostic="${i}">${esc(x)}</button>`).join('')}</div><p class="microcopy">No timer. A grown-up may read the words aloud.</p>`;document.querySelectorAll('[data-diagnostic]').forEach(b=>b.onclick=()=>{const correct=Number(b.dataset.diagnostic)===q.answer;d.answers.push({id:q.id,correct});if(correct)d.score++;d.index++;feedback(correct?'That place-value relationship is clear.':q.why,correct?'good':'try');save();setTimeout(()=>{feedback('');render()},500)})}
function renderBuild(){const t=track(),counts=Array.isArray(work.counts)?work.counts:[...t.target].map(()=>0);work={...work,counts};$('#activity').innerHTML=`<p class="eyebrow">BUILD WITH UNITS</p><h3>Build the number ${formatValue(valueOfCounts(t.target,t.places))}.</h3><p class="prompt">Add units to each place. Watch how the position changes their value.</p>${placeBoard(counts,true)}<button class="primary" data-action="checkBuild">Check my number</button>${controls()}${hint(`Match each digit to its place: ${t.target.map((n,i)=>`${n} ${placeName(t.places[i],n)}`).join(', ')}.`)}`;document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.count),delta=Number(b.dataset.delta);counts[i]=Math.max(0,Math.min(15,counts[i]+delta));saveSession({...work,counts});renderMission()})}
function checkBuild(){tryOnce();const t=track(),counts=work.counts||[];if(counts.length===t.target.length&&counts.every((n,i)=>n===t.target[i])){feedback(`Yes. ${t.target.map((n,i)=>`${n} ${placeName(t.places[i],n)}`).join(' + ')} makes ${formatValue(valueOfCounts(t.target,t.places))}.`,'good');complete(1,['unit','compose'])}else feedback(`Your model is worth ${formatValue(valueOfCounts(counts,t.places))}. Check which place needs a different number of units.`,'try')}
function renderTrade(){const t=track(),raw=[...t.trade],after=standardizeTrade(raw),traded=Boolean(work.traded);$('#activity').innerHTML=`<p class="eyebrow">SAME AMOUNT · NEW FORM</p><h3>Can we trade ten ${placeName(t.places[1])} for one ${placeName(t.places[0],1)}?</h3><p class="prompt">First notice the total. Then make the trade and check whether it changes.</p><div class="trade-stage"><div><span>BEFORE</span>${placeBoard(raw)}</div><div class="trade-arrow">${traded?'→':'?'}</div><div class="${traded?'':'trade-hidden'}"><span>AFTER</span>${traded?placeBoard(after):'<div class="mystery-card">Make one fair trade</div>'}</div></div>${traded?`<div class="answer-grid"><button class="choice" data-trade-proof="same">The total stayed ${formatValue(valueOfCounts(raw,t.places))}. Only the grouping changed.</button><button class="choice" data-trade-proof="more">The total became larger because the first place gained one.</button></div>`:'<button class="primary" data-action="trade">Trade ten smaller units</button>'}${controls()}${hint(`Ten ${placeName(t.places[1])} have the same value as one ${placeName(t.places[0],1)}. A fair trade changes the grouping, not the amount.`)}`;document.querySelectorAll('[data-trade-proof]').forEach(b=>b.onclick=()=>{tryOnce();if(b.dataset.tradeProof==='same'){feedback('Exactly. Regrouping is a fair exchange: the total stays the same.','good');complete(2,['unit','compose'])}else feedback('Compare the totals before and after. The first place gained value because ten smaller units were removed.','try')})}
function renderCompare(){const t=track(),[a,b]=t.compare,correct=compareNumbers(a,b);$('#activity').innerHTML=`<p class="eyebrow">LOOK LEFT FIRST</p><h3>Which number is greater?</h3><div class="compare-stage">${numberCard(a,t.places)}<span>?</span>${numberCard(b,t.places)}</div><div class="answer-grid compare-choices"><button class="choice" data-compare="left">${formatValue(a)} is greater</button><button class="choice" data-compare="equal">They are equal</button><button class="choice" data-compare="right">${formatValue(b)} is greater</button></div>${controls()}${hint(`Start with ${t.places[0].name.toLowerCase()}. Only move to the next place when those digits are equal.`)}`;document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{tryOnce();if(b.dataset.compare===correct){feedback('Correct. Now choose the reason that proves it.','good');showCompareWhy(a,b,t,correct)}else feedback(`Start at the greatest place: ${t.places[0].name}. A digit farther left has more value.`,'try')})}
function showCompareWhy(a,b,t,correct){const winner=correct==='left'?a:b;const loser=correct==='left'?b:a;const box=document.createElement('div');box.className='why-panel';box.innerHTML=`<p class="prompt">Why is ${formatValue(winner)} greater?</p><div class="answer-grid"><button class="choice" data-compare-why="correct">At the first place where the digits differ, ${formatValue(winner)} has the greater digit.</button><button class="choice" data-compare-why="wrong">It has a digit that looks bigger somewhere in the number.</button></div>`;$('#activity').append(box);box.querySelectorAll('[data-compare-why]').forEach(b=>b.onclick=()=>{tryOnce();if(b.dataset.compareWhy==='correct'){feedback(`Yes. Compare from ${t.places[0].name.toLowerCase()} toward the smaller places and stop at the first difference.`,'good');complete(3,['compare','explanation'],true)}else feedback('The place matters. Compare the same place in both numbers, starting with the greatest place.','try')})}
function renderFresh(){const due=state.retestDue||Date.now()+20*60*60*1000,ready=Date.now()>=due;if(!ready&&!state.previewFresh){const hours=Math.max(1,Math.ceil((due-Date.now())/3600000));$('#activity').innerHTML=`<div class="lock-card"><p class="eyebrow">FRESH CHECK</p><strong>Return after the model has faded from memory.</strong><p>About ${hours} hours remain. Waiting helps us see whether the idea is stable.</p><button class="secondary" data-action="preview">Preview for family review</button><p class="microcopy">The preview uses different numbers and will not count as delayed evidence.</p></div>`;return}const t=track(),[a,b]=ready?t.fresh.challenge:t.fresh.preview,correct=compareNumbers(a,b);$('#activity').innerHTML=`<p class="eyebrow">${ready?'DELAYED CHECK · NEW NUMBERS':'FAMILY PREVIEW · NOT DELAYED EVIDENCE'}</p><h3>Two shop labels show ${formatValue(a)} and ${formatValue(b)}. Which amount is greater?</h3><div class="compare-stage">${numberCard(a,t.places)}<span>?</span>${numberCard(b,t.places)}</div><div class="answer-grid"><button class="choice" data-fresh="left">${formatValue(a)}</button><button class="choice" data-fresh="equal">Equal</button><button class="choice" data-fresh="right">${formatValue(b)}</button></div><div id="freshWhy" hidden><p class="prompt">Which rule can you use every time?</p><div class="answer-grid"><button class="choice" data-fresh-why="correct">Compare the greatest place first. Move right only when the digits match.</button><button class="choice" data-fresh-why="wrong">Find the largest-looking digit anywhere.</button></div></div>${controls()}${hint(`Line up the places. Compare ${t.places[0].name.toLowerCase()} first.`)}`;let accepted=false;document.querySelectorAll('[data-fresh]').forEach(b=>b.onclick=()=>{tryOnce();if(b.dataset.fresh===correct){accepted=true;$('#freshWhy').hidden=false;feedback('The comparison is right. Now explain the reusable rule.','good')}else feedback('Line up the places and compare from the greatest place.','try')});document.querySelectorAll('[data-fresh-why]').forEach(b=>b.onclick=()=>{if(!accepted)return;tryOnce();if(b.dataset.freshWhy==='correct'){feedback(ready?'You used and explained place value with new numbers.':'Preview complete. Return later for fresh evidence.','good');complete(4,['compare','explanation'],false,!ready)}else feedback('Digits only have meaning through their place. Start with the greatest place.','try')})}
function renderComplete(i){const m=PLACE_CHAIN.missions[i];$('#activity').innerHTML=`<div class="complete-card"><div class="big-check">✓</div><p class="eyebrow">MISSION COMPLETE</p><h3>${esc(m.title)}</h3><p>Your work is saved for ${learner==='a'?'Ella':'Mila'}.</p>${i<4?'<button class="primary" data-action="next">Continue →</button>':'<a class="primary" href="./" style="text-decoration:none">Return home</a>'}</div>`}
function renderMission(){const i=state.activeMission,m=PLACE_CHAIN.missions[i];if(sessionMissionId!==m.id)loadSession(m.id);$('#missionEyebrow').textContent=`MISSION ${m.number} · ${m.kind.replace('-',' ').toUpperCase()}`;$('#missionTitle').textContent=m.title;$('#missionObjective').textContent=m.objective;$('#missionTime').textContent=`ABOUT ${m.minutes} MIN`;feedback('');if(done(i)){renderComplete(i);return}if(i===0)renderDiagnostic();else if(i===1)renderBuild();else if(i===2)renderTrade();else if(i===3)renderCompare();else renderFresh()}
function renderNav(){$('#missionNav').innerHTML=PLACE_CHAIN.missions.map((m,i)=>`<button class="mission-button ${i===state.activeMission?'active':''} ${unlocked(i)?'':'locked'}" data-mission="${i}" ${unlocked(i)?'':'disabled'}><span class="mission-number">${m.number}</span><span class="mission-label">${esc(m.title)}</span><span class="mission-state">${done(i)?'✓':unlocked(i)?'›':'◌'}</span></button>`).join('');document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>{state.activeMission=Number(b.dataset.mission);sessionMissionId=null;save();render()})}
function renderTrack(){const t=track();$('#trackCard').innerHTML=`<strong>Current depth: ${t.label}</strong><span>${t.description}</span><select id="trackSelect">${Object.values(PLACE_TRACKS).map(x=>`<option value="${x.id}" ${x.id===t.id?'selected':''}>${x.label}</option>`).join('')}</select><small>Changing depth restarts this review path so evidence is not mixed.</small>`;$('#trackSelect').onchange=e=>{state={...createBlankPlaceLearner(),track:e.target.value,family:state.family};sessionMissionId=null;save();render()}}
function renderEvidence(){const labels={unit:'Value of each unit',compose:'Build & trade ten',compare:'Compare by place',explanation:'Explain & transfer'};$('#evidenceGrid').innerHTML=Object.entries(labels).map(([k,v])=>`<div class="evidence-item"><header><span>${v}</span><span>${state.evidence[k]==='independent'?'Independent':state.evidence[k]==='learning'?'Learning':'Not checked'}</span></header></div>`).join('')}
function renderFamily(){$('#helpNote').value=state.family.help;$('#explainNote').value=state.family.explain;$('#continueNote').value=state.family.continue}
function render(){ensureState();$('#learnerSelect').value=learner;renderTrack();renderNav();renderEvidence();renderFamily();renderMission()}

document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='start'){state.missions['place-start']={complete:true,score:state.diagnostic.score,completedAt:new Date().toISOString()};state.activeMission=1;sessionMissionId=null;save();render()}else if(a==='next'){state.activeMission=Math.min(4,state.activeMission+1);sessionMissionId=null;save();render()}else if(a==='hint'){hintLevel++;saveSession();renderMission()}else if(a==='checkBuild')checkBuild();else if(a==='trade'){work={...work,traded:true};saveSession();renderMission()}else if(a==='preview'){state.previewFresh=true;save();render()}});
$('#learnerSelect').onchange=e=>{learner=e.target.value;state=readStore()[learner]||createBlankPlaceLearner();sessionMissionId=null;ensureState();save();render()};
for(const[id,key]of[['helpNote','help'],['explainNote','explain'],['continueNote','continue']])$('#'+id).addEventListener('input',e=>{state.family[key]=e.target.value;save()});
$('#resetPath').onclick=()=>{if(confirm(`Reset the place-value review path for ${learner==='a'?'Ella':'Mila'}?`)){state=createBlankPlaceLearner();sessionMissionId=null;save();render()}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
ensureState();render();
