export const uiEnglish={
  "学习记录保存在这台设备": "Progress is saved on this device",
  "浏览器未允许保存；本次仍可练习": "Saving is unavailable. You can still practice.",
  " / 约 5 分钟": " / About 5 minutes",
  "</p></div><span class=\"badge\">动手实验</span></div>": "</p></div><span class=\"badge\">Hands-on lab</span></div>",
  "把十分之一凑成整数": "Make one whole with tenths",
  "试着先凑满一个十": "Can you fill a ten-frame?",
  "点金色珠子，或把它拖到左边空格。想一想总数变了吗？": "Tap a gold bead, or drag it into the left frame. Does the total change?",
  "把补入的珠子放回右边": "Move a borrowed bead back",
  "移一颗到左边": "Move one bead left",
  "第一组": "First group",
  "第二组": "Second group",
  "<p style=\"text-align:center\">另有 ": "<p style=\"text-align:center\">Keep another ",
  "，保持不动。</p>": " unchanged.</p>",
  "<button data-act=\"move\" class=\"primary\">移一颗到左边</button><button data-act=\"back\">放回一颗</button><button data-act=\"resetModel\">重来</button>": "<button data-act=\"move\" class=\"primary\">Move one bead left</button><button data-act=\"back\">Move one back</button><button data-act=\"resetModel\">Start over</button>",
  "每一行一样多": "Equal rows",
  "改变行数和列数。再拆成两块，比较总数。": "Change the rows and columns. Split the array. Does the total change?",
  "行": "Rows",
  "列": "Columns",
  "合起来": "Join the parts",
  "拆成两块": "Split into two parts",
  "每行 ": "In each row: ",
  " 个，共 ": " objects. Rows: ",
  " 行": " rows",
  "一样大的整体": "The same size whole",
  "点到哪一份，就涂到哪一份。上下两条一样长。": "Tap a part to shade up to it. Both strips are the same length.",
  "点到哪一份，就涂到哪一份。再点涂色末端可减少一份。": "Tap a part to shade up to it. Tap the last shaded part to remove one.",
  "\" aria-label=\"涂到第 ": "\" aria-label=\"Shade through part ",
  " 份\">": "\">",
  "<p style=\"text-align:center\">试把 ": "<p style=\"text-align:center\">Combine ",
  " 与 ": " and ",
  " 合起来：涂 ": " by shading ",
  " 份。</p>": " parts.</p>",
  "<button data-act=\"less\">少涂一份</button><button class=\"primary\" data-act=\"more\">多涂一份</button><span>整体平均分成 ": "<button data-act=\"less\">Shade one fewer</button><button class=\"primary\" data-act=\"more\">Shade one more</button><span>Equal parts in this whole: ",
  " 份</span>": "</span>",
  "先猜，再换一个角度": "Predict, then turn",
  "拖动积木旋转；也可以用方向键或视角按钮。": "Drag to turn the blocks. You can also use arrow keys or view buttons.",
  "<div class=\"canvas-wrap\"><canvas id=\"blocks\" width=\"650\" height=\"320\" tabindex=\"0\" role=\"img\" aria-label=\"可旋转的单位积木模型，左右方向键旋转，上下方向键调整俯视角度\"></canvas></div><div class=\"view-controls\"><button data-view=\"front\">正面</button><button data-view=\"top\">上面</button><button data-view=\"side\">右面</button><button data-view=\"free\">立体</button></div>": "<div class=\"canvas-wrap\"><canvas id=\"blocks\" width=\"650\" height=\"320\" tabindex=\"0\" role=\"img\" aria-label=\"Rotating unit cubes. Left and right arrow keys turn; up and down keys tilt.\"></canvas></div><div class=\"view-controls\"><button data-view=\"front\">Front</button><button data-view=\"top\">Top</button><button data-view=\"side\">Right</button><button data-view=\"free\">3D</button></div>",
  " 列 × ": " columns × ",
  " 排": " rows",
  " 层": " layers",
  " · 高度不一样": " · Different heights",
  "</span><button data-act=\"count\" class=\"primary\">检查积木数量</button>": "</span><button data-act=\"count\" class=\"primary\">Check cube count</button>",
  "先找已知，再找问题": "What do you know? What do you need?",
  "先读故事，预测用哪一种运算。展开数量图检查。": "Read the story. Choose an operation. Open the bars to check your thinking.",
  "<div style=\"text-align:center;padding:30px\"><span class=\"pill\">先想一想：求一共，还是相差？</span></div>": "<div style=\"text-align:center;padding:30px\"><span class=\"pill\">What is the question asking you to find?</span></div>",
  "收起数量图": "Hide the bars",
  "打开数量图": "Show the bars",
  "每一步，怎样变化？": "What changes each time?",
  "有顺序，就不容易漏掉": "Try in order. Find every possibility.",
  "倒过来检查": "Work backward",
  "观察相邻两个数之间的变化。": "Look at the change between neighboring numbers.",
  "依次试每行放几个。只记录能排整齐的情况。": "Try different row sizes in order. Record only rows with no leftovers.",
  "先看一个例子，再自己解决不同的题。": "Explore this example. Then try a different problem on your own.",
  " 个方块</p><div class=\"mini-controls\">": " blocks</p><div class=\"mini-controls\">",
  "每行": "Per row",
  "可以排整齐：": "It fits: ",
  " 行，每行 ": " rows, with ",
  " 个。": " objects.",
  "不能排整齐，还剩 ": "It does not fit. Left over: ",
  "<div class=\"numbers\"><span>?</span><span>× 3</span><span>＋ 4</span><span>19</span></div><p style=\"text-align:center\">先撤掉 ＋4，再撤掉 ×3。想好后查看检查。</p>": "<div class=\"numbers\"><span>?</span><span>× 3</span><span>＋ 4</span><span>19</span></div><p style=\"text-align:center\">Undo +4 first. Then undo ×3. Think before checking.</p>",
  "<button data-act=\"logicHint\" class=\"primary\">查看思路</button>": "<button data-act=\"logicHint\" class=\"primary\">Show the method</button>",
  "</p></div><div style=\"text-align:right;margin-top:15px\"><button class=\"primary\" data-act=\"practice\">收起教具，独立试试 →</button></div>": "</p></div><div style=\"text-align:right;margin-top:15px\"><button class=\"primary\" data-act=\"practice\">Put the model away. Try on your own →</button></div>",
  "减少\">−</button><output>": ": decrease\">−</button><output>",
  "增加\">＋</button></div>": ": increase\">＋</button></div>",
  "<div class=\"story-line\"><span>小安</span><div class=\"bar\" style=\"width:": "<div class=\"story-line\"><span>Ann</span><div class=\"bar\" style=\"width:",
  "</div></div><div class=\"story-line\"><span>小贝</span><div class=\"bar orange\" style=\"width:": "</div></div><div class=\"story-line\"><span>Ben</span><div class=\"bar orange\" style=\"width:",
  "<p>先求 ": "<p>First find ",
  " 组，每组 ": " groups of ",
  "。然后拿走 ": ". Then take away ",
  "综合练习 · ": "Mixed practice · ",
  "数学拓展挑战": "Think deeper",
  "独立试试": "Try on your own",
  "</h3><p>没有计时。需要时可以看提示，之后再练独立完成。</p></div><span class=\"badge\">": "</h3><p>Take your time. Use a hint if you need one. Later, try without help.</p></div><span class=\"badge\">",
  "</h3><form id=\"answerForm\"><label for=\"answer\">你的答案": "</h3><form id=\"answerForm\"><label for=\"answer\">Your answer",
  "</label><div class=\"answer-row\"><input id=\"answer\" autocomplete=\"off\" inputmode=\"text\" placeholder=\"数字或分数\" required ": "</label><div class=\"answer-row\"><input id=\"answer\" autocomplete=\"off\" inputmode=\"text\" placeholder=\"Number or fraction\" required ",
  ">检查答案</button><button type=\"button\" data-act=\"hint\">给我一点提示</button></div></form><div id=\"hintBox\" class=\"hint\" ": ">Check answer</button><button type=\"button\" data-act=\"hint\">Give me a hint</button></div></form><div id=\"hintBox\" class=\"hint\" ",
  " style=\"margin-top:18px\">继续 →</button></div></div>": " style=\"margin-top:18px\">Continue →</button></div></div>",
  "你独立完成了。": "You solved it on your own. ",
  "借助检查，你找到了答案。": "You worked it out with help or another try. ",
  "还没对上。": "Not quite yet. ",
  " 可以修改后再试，或打开提示。": " You can change your answer or open a hint.",
  "<div class=\"lab summary\"><p class=\"overline\">这一小段，完成了</p><h3>": "<div class=\"lab summary\"><p class=\"overline\">This practice is complete</p><h3>",
  " 道独立完成</h3><p>这里记录的是本次练习表现，还需要隔天换题再检查。</p><ul>": " solved on your own</h3><p>This shows today's practice, not lasting mastery. Try different problems another day.</p><ul>",
  "独立完成": "On your own",
  "借助提示或修改后完成": "With a hint or another try",
  "</ul><div class=\"answer-row\"><button data-act=\"explore\">回到实验</button><button class=\"primary\" data-act=\"again\">": "</ul><div class=\"answer-row\"><button data-act=\"explore\">Back to the lab</button><button class=\"primary\" data-act=\"again\">",
  "再做一次（同题）": "Try the same challenge again",
  "换题再练": "Try new problems",
  "想一想：哪一步最有用？说清楚以后就可以休息。": "Which step helped most? Explain it, then take a break.",
  "左边凑满了！移动前后总数没有改变。": "The left frame is full! The total has not changed.",
  "观察两组数量，一组增加，另一组就减少。": "One group grows as the other shrinks. Watch both groups.",
  "已经回到开始状态。": "Back to the starting model.",
  "共有 ": "Total: ",
  " 个单位积木。按柱或按层数一数，再核对。": " unit cubes. Count by towers or layers to check.",
  "相邻两项都相差 ": "The difference between neighbors is ",
  "。再加一次试试。": ". Try adding it again.",
  "把行数和每行个数写成一对。互换后一样的排法，只算一次。": "Write the rows and row size as a pair. Count rotated rectangles only once.",
  "19−4=15，再算 15÷3=5。检查：5×3＋4=19。": "19 − 4 = 15. Then 15 ÷ 3 = 5. Check: 5 × 3 + 4 = 19.",
  "提示已打开。这题会记为借助帮助完成。": "Hint opened. This answer will be recorded as completed with help.",
  "拖动旋转 · 方向键也可以操作": "Drag to turn · Or use arrow keys",
  "答案已记录。": "Your answer is saved. ",
  "陪孩子发现，而不是代替作答": "Help your child discover",
  "<p>先问“你准备怎么试？”再给孩子时间。每次完成一个小任务即可休息。</p><ol><li>动手发现：观察模型，改变条件。</li><li>独立试试：收起模型，解答不同形式的问题。</li><li>想深一点：用有序列举、逆向思考解释原因。</li><li>隔天再练：检查离开提示后是否仍然会。</li></ol><p>题目可切换英文，帮助连接学校数学语言。两个学习者的记录分开保存在设备上。</p><p>当前是 18 个主题任务的起步版，覆盖部分 K–5 知识。综合练习是原创练习，不是官方 STAAR 试卷，也不预测考试分数。</p><a href=\"guide.html\">查看已覆盖内容、官方资料与安装说明 →</a>": "<p>Ask “What will you try?” Give your child time. One small activity is enough before a break.</p><ol><li>Explore: look at the model and change something.</li><li>Practice: put the model away and try different questions.</li><li>Think deeper: try organized lists or work backward. Explain why.</li><li>Try again another day without hints.</li></ol><p>The app is currently offered in English. Two learners have separate records on this device.</p><p>This starter has 18 activities on selected K–5 topics. It is not a complete curriculum or an official STAAR test, and it does not predict test scores.</p><a href=\"guide-en.html\">See coverage, references and installation →</a>",
  "学习足迹 · ": "Learning record · ",
  "探索者 A": "Ella",
  "探索者 B": "Mila",
  "<p>独立＝首次答对且未使用提示。练习表现不等于长期掌握；建议隔天换题再试。</p><table><thead><tr><th>任务</th><th>独立</th><th>有帮助</th><th>错误尝试</th></tr></thead><tbody>": "<p>On your own = correct on the first try, without a hint. This is practice, not proof of lasting mastery. Try different problems another day.</p><table><thead><tr><th>Activity</th><th>On your own</th><th>With help</th><th>Incorrect tries</th></tr></thead><tbody>",
  "<p>完成一道练习后，这里就会留下足迹。</p>": "<p>Finish a practice question to start your record.</p>",
  "<button id=\"clearRecords\" class=\"danger\">清除本学习者记录</button>": "<button id=\"clearRecords\" class=\"danger\">Clear this learner's record</button>",
  "确认清除当前学习者的练习记录与笔记？不能撤销，另一位学习者不受影响。": "Clear this learner's practice and notes? This cannot be undone. The other learner's record will stay.",
  " · 离线缓存尚未就绪": " · Offline files are not ready yet"
};
